server:
  port: 3000  # Cổng của server chạy
  servlet:
    context-path: "/"  # Đường dẫn gốc của ứng dụng, truy cập tại http://localhost:3000/

spring:
  devtools:
    restart:
      enabled: true  # Bật tính năng hot reload khi code thay đổi

  datasource:
    url: jdbc:mysql://localhost:3306/Quiz  # Thêm tên của database "Quiz"
    username: root  # Tài khoản MySQL
    password: 123456  # Mật khẩu MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver  # Driver JDBC cho MySQL

  jpa:
    hibernate:
      ddl-auto: update  # Tự động cập nhật schema database
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Chọn MySQL8Dialect cho Hibernate
    show-sql: true  # Hiển thị câu lệnh SQL trong console
